services:
  db:
    image: postgres:16.3
    container_name: my-postgres
    ports:
      - 15432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_sql_scripts:/docker-entrypoint-initdb.d


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: